### PR TITLE
update to hugo 0.76.4

### PR DESCRIPTION
**Pull request by gavinr**

### CODE REVIEW

**Comment by gavinr** [comment]
Updated for https://github.com/gohugoio/hugo/releases/tag/v0.76.4

**Comment by gavinr** [comment]
Updated for https://github.com/gohugoio/hugo/releases/tag/v0.76.5

**Comment by jojomi** [comment]
Sorry for the delay and thanks for the reminder.

I created builds for the recently released versions.

**Comment by gavinr** [comment]
@jojomi thank you!

**Pull request closed without merging**
