### PR TITLE
removed pid 1 zombie issue, removed run.sh loop and sleep timers

### PR DESCRIPTION
**Pull request by fitz123**
minimizing Dockerfile

### CODE REVIEW

**Comment by jojomi** [comment]
@fitz123 Thank you for your effort. I like your changes to the Dockerfile. But you removed the loop which I explained in #10.

What is your reason for removing it? :)

**Comment by fitz123** [comment]
because it works without the loop for me just fine using, for example this:
```
docker run \
        --rm \
        -v $(pwd)/src:/src \
        -v $(pwd)/output:/output \
        -e HUGO_WATCH=true \
        --net host \
        hugo
```

**Comment by jojomi** [comment]
My use-case was "planned content" (to be visible at a future date) without a content change. Watching does not work there, neither does one-time generation or do I miss something there?

**Comment by fitz123** [comment]
if I got you right, you use case is followed:
1. Run hugo = generate site once, serve by build-in server
2. Modify content (src folder) and and do not SHOW result just yet
3. Update result after predictable amount of time

If so, then you need to run it in the _server mode_, **without** WATCH option
When you need to update the content - just restart container. 
profit

**Comment by fitz123** [comment]
I use these as a README for my developers. I think that's workflow covers all cases

### Generate site

```
docker run \
        --rm
        -v $(pwd)/src:/src \
        -v $(pwd)/output:/output \
        --net host \
        hugo
```

### Serve site

```
docker run \
        --rm \
        -v $(pwd)/output:/usr/share/nginx/html \
        --net host \
        nginx
```

http://localhost

### Generate & serve & auto-regenerate during development

```
docker run \
        --rm \
        -v $(pwd)/src:/src \
        -v $(pwd)/output:/output \
        -e HUGO_WATCH=true \
        --net host \
        hugo
```

http://localhost:1313

**Pull request closed without merging**
